In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/muestras_calidad_agua.csv')
df

                           sitio   pH  oxigeno  temperatura
0                 Río Subachoque  7.2      7.8         18.5
1    Quebrada Honda (Facatativá)  6.3      6.2         19.4
2           Río Botello (Madrid)  6.8      5.9         22.7
3   Afluente San José (El Rosal)  7.9      8.3         20.1
4                    Río Villeta  8.7      6.1         28.3
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2
6            Río Tobia (Nocaima)  7.4      5.2         26.9
7       Quebrada Negra (La Vega)  7.6      7.0         24.4
8          Río Bahamón (Sasaima)  8.1      6.7         27.6
9        Río Guayuriba (La Mesa)  5.9      4.8         30.5

In [3]:
df_temp = df[['sitio', 'temperatura']]
df_temp

                           sitio  temperatura
0                 Río Subachoque         18.5
1    Quebrada Honda (Facatativá)         19.4
2           Río Botello (Madrid)         22.7
3   Afluente San José (El Rosal)         20.1
4                    Río Villeta         28.3
5  Quebrada Cune (San Francisco)         25.2
6            Río Tobia (Nocaima)         26.9
7       Quebrada Negra (La Vega)         24.4
8          Río Bahamón (Sasaima)         27.6
9        Río Guayuriba (La Mesa)         30.5

In [4]:
df_temp['categoria_temp'] = np.where(
    df_temp['temperatura'] < 20,
    'fría',
    np.where(
        df_temp['temperatura'] <= 25,
        'templada',
        'caliente'
    )
)

df_temp

/tmp/ipykernel_1301/2472040300.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp['categoria_temp'] = np.where(

                           sitio  temperatura categoria_temp
0                 Río Subachoque         18.5           fría
1    Quebrada Honda (Facatativá)         19.4           fría
2           Río Botello (Madrid)         22.7       templada
3   Afluente San José (El Rosal)         20.1       templada
4                    Río Villeta         28.3       caliente
5  Quebrada Cune (San Francisco)         25.2       caliente
6            Río Tobia (Nocaima)         26.9       caliente
7       Quebrada Negra (La Vega)         24.4       templada
8          Río Bahamón (Sasaima)         27.6       caliente
9        Río Guayuriba (La Mesa)         30.5       caliente

In [5]:
df_temp['riesgo_termico'] = np.where(
    df_temp['temperatura'] > 25,
    'Sí',
    'No'
)

df_temp

                           sitio  temperatura categoria_temp riesgo_termico
0                 Río Subachoque         18.5           fría             No
1    Quebrada Honda (Facatativá)         19.4           fría             No
2           Río Botello (Madrid)         22.7       templada             No
3   Afluente San José (El Rosal)         20.1       templada             No
4                    Río Villeta         28.3       caliente             Sí
5  Quebrada Cune (San Francisco)         25.2       caliente             Sí
6            Río Tobia (Nocaima)         26.9       caliente             Sí
7       Quebrada Negra (La Vega)         24.4       templada             No
8          Río Bahamón (Sasaima)         27.6       caliente             Sí
9        Río Guayuriba (La Mesa)         30.5       caliente             Sí

In [6]:
df_caliente = df_temp[df_temp['temperatura'] > 25]

df_caliente

                           sitio  temperatura categoria_temp riesgo_termico
4                    Río Villeta         28.3       caliente             Sí
5  Quebrada Cune (San Francisco)         25.2       caliente             Sí
6            Río Tobia (Nocaima)         26.9       caliente             Sí
8          Río Bahamón (Sasaima)         27.6       caliente             Sí
9        Río Guayuriba (La Mesa)         30.5       caliente             Sí

In [7]:
df_temp.to_csv('resultado_temperatura.csv', index=False)

In [8]:
porcentaje = (
    (df_temp['riesgo_termico'] == 'Sí').sum()
    / len(df_temp)
) * 100

print(f'Porcentaje con riesgo térmico: {porcentaje:.1f}%')

Porcentaje con riesgo térmico: 50.0%

En este reto se analiza la temperatura del agua en diferentes sitios de Cundinamarca utilizando condicionales y herraminetas pandas, para clasificar la temperatura de cada sitio y asi establecer si hay riesgo en el cuerpo de agua.