# 🧩 Reto 2 – pH
**Objetivo:** clasificar pH y generar alerta química.

**Datos:** `../data/muestras_calidad_agua.csv`

# Reto 2 - Evaluación de pH y alerta química

## Objetivo
Analizar los valores de pH de diferentes cuerpos de agua en Cundinamarca utilizando condicionales en Python para identificar posibles riesgos químicos y clasificar la calidad del agua.

### Variables analizadas
- pH
- Clasificación química
- Nivel de alerta ambiental

### Autor
Estudiante 2

In [9]:
import pandas as pd

print("Pandas cargado correctamente")

Pandas cargado correctamente

In [11]:
df = pd.read_csv("../data/muestras_calidad_agua.csv")

In [12]:
df

                           sitio   pH  oxigeno  temperatura
0                 Río Subachoque  7.2      7.8         18.5
1    Quebrada Honda (Facatativá)  6.3      6.2         19.4
2           Río Botello (Madrid)  6.8      5.9         22.7
3   Afluente San José (El Rosal)  7.9      8.3         20.1
4                    Río Villeta  8.7      6.1         28.3
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2
6            Río Tobia (Nocaima)  7.4      5.2         26.9
7       Quebrada Negra (La Vega)  7.6      7.0         24.4
8          Río Bahamón (Sasaima)  8.1      6.7         27.6
9        Río Guayuriba (La Mesa)  5.9      4.8         30.5

In [13]:
print("Promedio de pH:", df["pH"].mean())
print("pH mínimo:", df["pH"].min())
print("pH máximo:", df["pH"].max())

Promedio de pH: 7.19
pH mínimo: 5.9
pH máximo: 8.7

In [15]:
def clasificar_ph(ph):

    if ph < 6.5:
        return "Ácida"

    elif ph <= 8.5:
        return "Neutra"

    else:
        return "Alcalina"

In [16]:
df["clasificacion_pH"] = df["pH"].apply(clasificar_ph)

In [17]:
df

                           sitio   pH  oxigeno  temperatura clasificacion_pH
0                 Río Subachoque  7.2      7.8         18.5           Neutra
1    Quebrada Honda (Facatativá)  6.3      6.2         19.4            Ácida
2           Río Botello (Madrid)  6.8      5.9         22.7           Neutra
3   Afluente San José (El Rosal)  7.9      8.3         20.1           Neutra
4                    Río Villeta  8.7      6.1         28.3         Alcalina
5  Quebrada Cune (San Francisco)  6.0      4.5         25.2            Ácida
6            Río Tobia (Nocaima)  7.4      5.2         26.9           Neutra
7       Quebrada Negra (La Vega)  7.6      7.0         24.4           Neutra
8          Río Bahamón (Sasaima)  8.1      6.7         27.6           Neutra
9        Río Guayuriba (La Mesa)  5.9      4.8         30.5            Ácida

In [18]:
def alerta_quimica(ph):

    if ph < 6:
        return "⚠️ Alta acidez"

    elif ph < 6.5:
        return "⚠️ Riesgo moderado"

    elif ph <= 8.5:
        return "✅ Condición estable"

    else:
        return "⚠️ Riesgo por alcalinidad"

In [19]:
df["alerta_quimica"] = df["pH"].apply(alerta_quimica)

In [20]:
df

,sitio,pH,oxigeno,temperatura,clasificacion_pH,alerta_quimica
0,Río Subachoque,7.2,7.8,18.5,Neutra,✅ Condición estable
1,Quebrada Honda (Facatativá),6.3,6.2,19.4,Ácida,⚠️ Riesgo moderado
2,Río Botello (Madrid),6.8,5.9,22.7,Neutra,✅ Condición estable
3,Afluente San José (El Rosal),7.9,8.3,20.1,Neutra,✅ Condición estable
4,Río Villeta,8.7,6.1,28.3,Alcalina,⚠️ Riesgo por alcalinidad
5,Quebrada Cune (San Francisco),6.0,4.5,25.2,Ácida,⚠️ Riesgo moderado
6,Río Tobia (Nocaima),7.4,5.2,26.9,Neutra,✅ Condición estable
7,Quebrada Negra (La Vega),7.6,7.0,24.4,Neutra,✅ Condición estable
8,Río Bahamón (Sasaima),8.1,6.7,27.6,Neutra,✅ Condición estable
9,Río Guayuriba (La Mesa),5.9,4.8,30.5,Ácida,⚠️ Alta acidez

In [21]:
sitios_riesgo = df[
    (df["pH"] < 6.5) | (df["pH"] > 8.5)
]

sitios_riesgo

,sitio,pH,oxigeno,temperatura,clasificacion_pH,alerta_quimica
1,Quebrada Honda (Facatativá),6.3,6.2,19.4,Ácida,⚠️ Riesgo moderado
4,Río Villeta,8.7,6.1,28.3,Alcalina,⚠️ Riesgo por alcalinidad
5,Quebrada Cune (San Francisco),6.0,4.5,25.2,Ácida,⚠️ Riesgo moderado
9,Río Guayuriba (La Mesa),5.9,4.8,30.5,Ácida,⚠️ Alta acidez

In [22]:
print("Número de sitios con posible alteración química:")
print(len(sitios_riesgo))

Número de sitios con posible alteración química:
4

In [23]:
df

,sitio,pH,oxigeno,temperatura,clasificacion_pH,alerta_quimica
0,Río Subachoque,7.2,7.8,18.5,Neutra,✅ Condición estable
1,Quebrada Honda (Facatativá),6.3,6.2,19.4,Ácida,⚠️ Riesgo moderado
2,Río Botello (Madrid),6.8,5.9,22.7,Neutra,✅ Condición estable
3,Afluente San José (El Rosal),7.9,8.3,20.1,Neutra,✅ Condición estable
4,Río Villeta,8.7,6.1,28.3,Alcalina,⚠️ Riesgo por alcalinidad
5,Quebrada Cune (San Francisco),6.0,4.5,25.2,Ácida,⚠️ Riesgo moderado
6,Río Tobia (Nocaima),7.4,5.2,26.9,Neutra,✅ Condición estable
7,Quebrada Negra (La Vega),7.6,7.0,24.4,Neutra,✅ Condición estable
8,Río Bahamón (Sasaima),8.1,6.7,27.6,Neutra,✅ Condición estable
9,Río Guayuriba (La Mesa),5.9,4.8,30.5,Ácida,⚠️ Alta acidez

# Conclusiones

- Se identificaron cuerpos de agua con condiciones ácidas y alcalinas.
- Los valores extremos de pH pueden afectar la biodiversidad acuática.
- El uso de condicionales permitió automatizar la clasificación ambiental.
- Python y pandas facilitan el análisis de datos ambientales reales.